spring:
  application:
    name: movieFlix

  datasource:
    url: jdbc:postgresql://localhost:5432/movieflix
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update


  flyway:
    enabled: true
    baseline-on-migrate: true


server:
    port: 8082

movieflix:
  security:
    secret: "nossa nossa assim vc me mata, ai se eu te pego,ai se eu te pego"

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html